name: Publish Luhmann Archive
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Henter hele historikken, hvilket MkDocs godt kan lide

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          # cache: 'pip' CKommenteret ud for at undgå fejl med deployment

      - run: pip install mkdocs-material mkdocs-roamlinks-plugin

      - run: mkdocs gh-deploy --force